packages:
  - packages/**
  - tooling/**

catalogs:
  prod:
    "pretty-bytes": ^7.1.0
    '@pixpilot/hash': ^0.0.0
    "@pixpilot/string": ^2.3.0
    "@pixpilot/env": ^0.2.2
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-react: 0.553.0
    next-themes: 0.4.6
    react: 19.2.0
    react-dom: 19.2.0
    tailwind-merge: ^3.4.0
    "@iconify/react": ^6.0.2
    "@iconify-json/fa": ^1.2.2
    "@iconify-json/mdi": ^1.2.3
    "@iconify-json/tabler": ^1.2.23

  dev:
    '@chromatic-com/storybook': ^4.1.3
    '@pixpilot/dev-config': ^3.17.0
    '@storybook/addon-essentials': ^8.6.14
    '@storybook/addon-interactions': ^8.6.14
    '@storybook/addon-links': ^8.6.14
    '@storybook/addon-themes': ^8.6.14
    '@storybook/blocks': ^8.6.14
    '@storybook/react': ^8.6.14
    '@storybook/react-vite': ^8.6.14
    '@storybook/test': ^8.6.14
    '@tailwindcss/postcss': ^4.1.18
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.3.0
    '@types/node': ^22.19.3
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    autoprefixer: ^10.4.23
    eslint: ^9.39.2
    glob: ^11.1.0
    prettier: ^3.7.4
    storybook: ^8.6.14
    tailwindcss: ^4.1.18
    tailwindcss-animate: ^1.0.7
    tsdown: ^0.15.12
    typescript: ^5.9.3
    typescript-eslint: ^8.49.0
    vite: ^7.3.1
    vitest: ^3.2.4
    jsdom: ^27.3.0
