packages:
  - packages/**
  - tooling/**

catalogs:
  prod:
    "pretty-bytes": ^7.1.0
    '@pixpilot/hash': ^0.0.0
    "@pixpilot/string": ^2.3.0
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-react: 0.553.0
    next-themes: 0.4.6
    react: 19.2.0
    react-dom: 19.2.0
    tailwind-merge: ^3.4.0

  dev:
    '@chromatic-com/storybook': ^4.1.3
    '@pixpilot/dev-config': ^3.16.0
    '@storybook/addon-essentials': ^8.5.3
    '@storybook/addon-interactions': ^8.5.3
    '@storybook/addon-links': ^8.5.3
    '@storybook/addon-themes': ^8.5.3
    '@storybook/blocks': ^8.5.3
    '@storybook/react': ^8.5.3
    '@storybook/react-vite': ^8.5.3
    '@storybook/test': ^8.5.3
    '@tailwindcss/postcss': ^4.1.0
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.3.0
    '@types/node': ^22.18.11
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    autoprefixer: ^10.4.20
    eslint: ^9.38.0
    glob: ^11.0.3
    prettier: ^3.6.2
    storybook: ^8.5.3
    tailwindcss: ^4.1.0
    tailwindcss-animate: ^1.0.7
    tsdown: ^0.17.0
    typescript: ^5.9.3
    typescript-eslint: ^8.46.3
    vite: ^6.1.3
    vitest: ^3.2.4
