packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@pixpilot/dev-config': ^3.16.0
    '@testing-library/jest-dom': ^6.9.1
    '@testing-library/react': ^16.3.0
    '@types/node': ^22.18.11
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.2
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint: ^9.38.0
    glob: ^11.0.3
    prettier: ^3.6.2
    tsdown: ^0.15.8
    typescript-eslint: ^8.46.3
    typescript: ^5.9.3
    vitest: ^3.2.4

  prod:
    '@pixpilot/hash': ^0.0.0
    next-themes: 0.4.6
    react-dom: 19.1.1
    react: 19.1.1
    tailwind-merge: ^3.4.0
    "clsx": "^2.1.1"
    "lucide-react": "^0.553.0"
    class-variance-authority: "^0.7.1"