import type { ComponentMeta, OwnProps } from '@internal/mcp';
import type { DatePickerProps } from './DatePicker';
import { defineProps } from '@internal/mcp';

type DatePickerOwnProps = OwnProps<DatePickerProps, 'button'>;

export const meta: ComponentMeta<DatePickerOwnProps> = {
  name: 'DatePicker',
  category: 'Formily Inputs',
  description: 'A Formily-connected date picker field for selecting a single date value.',
  htmlElement: 'button',
  props: defineProps<DatePickerOwnProps>({
    footer: 'Forwarded to the underlying UI component.',
    animate: 'Forwarded to the underlying UI component.',
    components: 'Forwarded to the underlying UI component.',
    required: 'Marks the control as required for accessibility and UI state.',
    placeholder: 'Placeholder text shown before a value is selected or entered.',
    classNames: 'Forwarded to the underlying UI component.',
    modifiersClassNames: 'Forwarded to the underlying UI component.',
    styles: 'Forwarded to the underlying UI component.',
    modifiersStyles: 'Forwarded to the underlying UI component.',
    defaultMonth: 'Forwarded to the underlying UI component.',
    month: 'Forwarded to the underlying UI component.',
    numberOfMonths: 'Forwarded to the underlying UI component.',
    startMonth: 'Forwarded to the underlying UI component.',
    fromDate: 'Forwarded to the underlying UI component.',
    fromMonth: 'Forwarded to the underlying UI component.',
    fromYear: 'Forwarded to the underlying UI component.',
    endMonth: 'Forwarded to the underlying UI component.',
    toDate: 'Forwarded to the underlying UI component.',
    toMonth: 'Forwarded to the underlying UI component.',
    toYear: 'Forwarded to the underlying UI component.',
    pagedNavigation: 'Forwarded to the underlying UI component.',
    reverseMonths: 'Forwarded to the underlying UI component.',
    hideNavigation: 'Forwarded to the underlying UI component.',
    disableNavigation: 'Forwarded to the underlying UI component.',
    captionLayout: 'Forwarded to the underlying UI component.',
    reverseYears: 'Forwarded to the underlying UI component.',
    navLayout: 'Forwarded to the underlying UI component.',
    fixedWeeks: 'Forwarded to the underlying UI component.',
    hideWeekdays: 'Forwarded to the underlying UI component.',
    showOutsideDays: 'Forwarded to the underlying UI component.',
    showWeekNumber: 'Forwarded to the underlying UI component.',
    broadcastCalendar: 'Forwarded to the underlying UI component.',
    ISOWeek: 'Forwarded to the underlying UI component.',
    timeZone: 'Forwarded to the underlying UI component.',
    noonSafe: 'Forwarded to the underlying UI component.',
    initialFocus: 'Forwarded to the underlying UI component.',
    today: 'Forwarded to the underlying UI component.',
    modifiers: 'Forwarded to the underlying UI component.',
    labels: 'Forwarded to the underlying UI component.',
    formatters: 'Forwarded to the underlying UI component.',
    locale: 'Forwarded to the underlying UI component.',
    numerals: 'Forwarded to the underlying UI component.',
    weekStartsOn: 'Forwarded to the underlying UI component.',
    firstWeekContainsDate: 'Forwarded to the underlying UI component.',
    useAdditionalWeekYearTokens: 'Forwarded to the underlying UI component.',
    useAdditionalDayOfYearTokens: 'Forwarded to the underlying UI component.',
    onMonthChange: 'Forwarded to the underlying UI component.',
    onNextClick: 'Forwarded to the underlying UI component.',
    onPrevClick: 'Forwarded to the underlying UI component.',
    onWeekNumberClick: 'Forwarded to the underlying UI component.',
    onDayClick: 'Forwarded to the underlying UI component.',
    onDayFocus: 'Forwarded to the underlying UI component.',
    onDayBlur: 'Forwarded to the underlying UI component.',
    onDayKeyDown: 'Forwarded to the underlying UI component.',
    onDayMouseEnter: 'Forwarded to the underlying UI component.',
    onDayMouseLeave: 'Forwarded to the underlying UI component.',
    dateLib: 'Forwarded to the underlying UI component.',
    onDayKeyUp: 'Forwarded to the underlying UI component.',
    onDayKeyPress: 'Forwarded to the underlying UI component.',
    onDayPointerEnter: 'Forwarded to the underlying UI component.',
    onDayPointerLeave: 'Forwarded to the underlying UI component.',
    onDayTouchCancel: 'Forwarded to the underlying UI component.',
    onDayTouchEnd: 'Forwarded to the underlying UI component.',
    onDayTouchMove: 'Forwarded to the underlying UI component.',
    onDayTouchStart: 'Forwarded to the underlying UI component.',
    buttonVariant: 'Forwarded to the underlying UI component.',
    showClearButton: 'Forwarded to the underlying UI component.',
  }),
  examples: [
    {
      title: 'Declarative schema field',
      code: `<SchemaField.String name="datePicker" title="DatePicker" x-decorator="FormItem" x-component="DatePicker" />`,
    },
    {
      title: 'JSON schema for form renderer',
      code: `{
  type: 'object',
  properties: {
    datePicker: {
      type: 'string',
      title: 'DatePicker',
      'x-decorator': 'FormItem',
      'x-component': 'DatePicker',
    },
  },
}`,
    },
  ],
  keywords: ['formily', 'date', 'picker', 'calendar'],
};
